### ISSUE TITLE
Supprimer les configurations redondantes et/ou inutiles.

### ISSUE THREAD

**Issue by Aldarone** [Oros42/firefox_change_prefs#1]
Dans la liste de ces préférences il y en a quelques une qui ne servent à rien et d'autres qui font double emploi.

Je les détaille ici : 

```
user_pref("loop.enabled",true); // Active Firefox Hello
```

Par défaut cette valeur est déjà sur `true`. De plus à cause de `user_pref("media.peerconnection.enabled",false);` WebRTC est désactivé ce qui rend Firefox Hello inopérant.

```
user_pref("security.ssl3.dhe_rsa_aes_128_sha",false);
user_pref("security.ssl3.dhe_rsa_aes_256_sha",false);
```

Ces deux là concernent des ciphers SSLv3 or le protocole est déjà désactivé par `user_pref("security.tls.version.min",2);` qui force l'usage de TLSv1.1 au minimum.

```
user_pref("privacy.trackingprotection.enabled",false);
```

Désactive la protection anti-tracking apparue dans Firefox 35, cette protection est encore désactivée par défaut.

**Comment by Oros42** [comment]
Okay je vais corriger ça.

Par contre, si l'on repasse security.tls.version.min à 1 (genre pour consulter momentanément shaarli.fr), security.ssl3.dhe_rsa_aes_128_sha et security.ssl3.dhe_rsa_aes_256_sha servent ou pas ?

**Comment by Aldarone** [comment]
Non, parce que SSLv3 correspond à la valeur 0. Et cette valeur est à 1 par défaut (TLSv1) depuis Firefox 34 : https://blog.mozilla.org/security/2014/10/14/the-poodle-attack-and-the-end-of-ssl-3-0/

**Comment by Oros42** [comment]
Okay merci.
Je fini les modifs et je commit.
